name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Run Build SCript
        shell: pwsh
        run: |
          ./build.ps1
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          xunit_files: "dist/*.trx"
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "dist/*.xml"
          badge: true
      - name: Download Artifact
        uses: actions/download-artifact@master
        if: github.tag != ''
        with:
          name: app
          path: "dist/*.zip"
